name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Checkout MacKernelSDK
        uses: actions/checkout@v3
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - name: Build project
        run: xcodebuild -configuration=Release

      - name: List build output files
        run: ls -alh build/Release # Check if there are files in the output directory

      - name: Package build output
        run: zip -r build_output.zip build/Release/* # Create a zip file of the build output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/Release

      - name: Upload build
        uses: svenstaro/upload-release-action@2.9.0
        if: github.event_name != 'pull_request'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build_output.zip # Reference the created zip file
          tag: ${{ github.ref }}
          release_name: HoRNDIS
          body: Update objective-c-xcode.yml
          file_glob: false
          overwrite: true
